name: build
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome --screenshots-full-page -s e2e/screens --color -a 'npm run serve' e2e/cases"
        env:
          BASE_URL: http://localhost:3000
          WINDOW_DPI: 1
